[phases.setup]
nixPkgs = ['python311', 'nodejs_18']

[phases.install]
cmds = [
    'cd simulation_engine && pip install -r requirements.txt',
    'cd frontend && npm install'
]

[phases.build]
cmds = [
    'cd frontend && npm run build'
]

[start]
cmd = "uvicorn simulation_engine.main:app --host 0.0.0.0 --port $PORT"
